### ISSUE TITLE
Problem with local characters

### ISSUE THREAD

**Issue by paszczakojad** [themaks/embrace_decryptor#4]
While decrypting some files with local characters I got following error:

[+] Decrypting file /home/samba/#_Komp GS/backup.ransomware/Users/Piotr/Documents/Otis - zapytanie o studzienkÄ.odt.[pain@cock.lu].pain
Traceback (most recent call last):
  File "decrypt/embrace_decryptor-master/decrypt_file.py", line 203, in <module>
    decrypted_content = try_unlock_file(filename, decryptiontime=decryptiontime, delta=args.delta)
  File "decrypt/embrace_decryptor-master/decrypt_file.py", line 130, in try_unlock_file
    return decrypt_file(filecontent, filename, decryptiontime)
  File "decrypt/embrace_decryptor-master/decrypt_file.py", line 88, in decrypt_file
    IV = derive_IV_from_filename(filename)
  File "decrypt/embrace_decryptor-master/decrypt_file.py", line 77, in derive_IV_from_filename
    return bytes_to_str(filename_16_last_rev)
  File "decrypt/embrace_decryptor-master/decrypt_file.py", line 33, in bytes_to_str
    return "".join(map(chr, b))
ValueError: chr() arg not in range(256)

I did that under Linux and I think these chars are UTF-8 encoded.

Besides that - the tool works perfectly, thanks :)

**Comment by themaks** [comment]
This commit should stop the tool from crashing. 
https://github.com/themaks/embrace_decryptor/commit/819e9be9bfc3a9ded7dc580a397078d178d6c86b
However, maybe the first block (16 bytes) of the decrypted file will not be decrypted correctly.
